/** Live client sites — URLs normalized to https where omitted in source list. */
export const projects = [
  {
    title: "Journey 360",
    role: "Full stack · travel",
    year: "2022 — Present",
    tags: ["PHP", "Laravel", "Travel"],
    desc: "UK travel discovery with itinerary-led storytelling and clear conversion paths.",
    url: "https://www.journey360.co.uk/",
  },
  {
    title: "Flights Journey",
    role: "Landing · performance",
    year: "2022 — Present",
    tags: ["HTML", "CSS", "JavaScript"],
    desc: "Campaign landing for flight offers — lean markup and strong above-the-fold CTAs.",
    url: "https://landing.flightsjourney.co.uk/",
  },
  {
    title: "Umrah Experts",
    role: "Full stack · pilgrimage",
    year: "2022 — Present",
    tags: ["Laravel", "MySQL", "UX"],
    desc: "Premium Umrah packages with trust signals, FAQs, and frictionless inquiries.",
    url: "https://www.umrahexperts.co.uk/",
  },
  {
    title: "Fly to World",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["PHP", "Responsive"],
    desc: "Global flight positioning with mobile-first layouts and scannable deal blocks.",
    url: "https://flytoworld.co.uk/",
  },
  {
    title: "Miraaj Travel",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["Bootstrap", "Travel"],
    desc: "Spiritual journey brand site balancing editorial content with booking prompts.",
    url: "https://www.miraajtravel.co.uk/",
  },
  {
    title: "Holiday Deals UK",
    role: "Landing",
    year: "2022 — Present",
    tags: ["JavaScript", "SEO"],
    desc: "Seasonal holiday deals hub tuned for paid traffic and fast first paint.",
    url: "https://landing.holidaydealsuk.co.uk/",
  },
  {
    title: "Tour Vibes",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["PHP", "MySQL"],
    desc: "Tour packaging and group-travel narratives with gallery-rich detail pages.",
    url: "https://www.tourvibes.co.uk/",
  },
  {
    title: "Kaabah Tours",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["Laravel", "Travel"],
    desc: "Islamic travel specialist with package comparison and inquiry workflows.",
    url: "https://kaabahtours.com/",
  },
  {
    title: "Islamic Travel Agency (UK)",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["PHP", "MySQL"],
    desc: "Full-service Hajj and Umrah presence for the UK market.",
    url: "https://www.islamictravelagency.co.uk/",
  },
  {
    title: "Premier Flights",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["JavaScript", "Bootstrap"],
    desc: "Flight-focused site with carrier highlights and streamlined result patterns.",
    url: "https://premierflights.co.uk/",
  },
  {
    title: "Umrah Packages",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["Laravel", "Forms"],
    desc: "Package grids and family-oriented consultation flows for Umrah planning.",
    url: "https://www.umrahpackagess.co.uk/",
  },
  {
    title: "Airlines House",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["PHP", "Responsive"],
    desc: "Airline deals hub with modular content blocks per carrier and route.",
    url: "https://www.airlineshouse.co.uk/",
  },
  {
    title: "Road to Haram",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["HTML", "CSS", "Travel"],
    desc: "Narrative-led pilgrimage travel with emphasis on clarity and reassurance.",
    url: "https://www.roadtoharam.co.uk/",
  },
  {
    title: "Travixum",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["Bootstrap", "JavaScript"],
    desc: "Contemporary travel brand with modular sections and strong typography.",
    url: "https://www.travixum.co.uk/",
  },
  {
    title: "Mid Holidays",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["Laravel", "MySQL"],
    desc: "Core holiday brand — packages, escapes, and seasonal promotional pages.",
    url: "https://midholidays.co.uk/",
  },
  {
    title: "Mid Holidays — Landing",
    role: "Campaign landing",
    year: "2022 — Present",
    tags: ["Performance", "Landing"],
    desc: "Dedicated funnel for promos and paid campaigns alongside the main brand.",
    url: "https://landing.midholidays.co.uk/",
  },
  {
    title: "Travel Mart UK",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["PHP", "Travel"],
    desc: "Aggregated offers with category-first navigation for quick scanning.",
    url: "https://travelmartuk.co.uk/",
  },
  {
    title: "Bismillah Travel",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["Laravel", "UK"],
    desc: "UK Islamic travel operator with booking-led information architecture.",
    url: "https://bismillahtravel.co.uk/",
  },
  {
    title: "Bismillah Travel (staging)",
    role: "Development",
    year: "2022 — Present",
    tags: ["Laravel", "QA"],
    desc: "Staging environment for safe iteration before production releases.",
    url: "https://dev.bismillahtravel.co.uk/",
  },
  {
    title: "Urban Tours",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["Bootstrap", "Gallery"],
    desc: "City breaks and urban experiences with image-forward layouts.",
    url: "https://www.urbantours.co.uk/",
  },
  {
    title: "Baitullah Travel",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["PHP", "MySQL"],
    desc: "Hajj and Umrah focus with package clarity and supportive copy throughout.",
    url: "https://www.baitullahtravel.co.uk/",
  },
  {
    title: "Flights Edge",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["JavaScript", "SEO"],
    desc: "Competitive flight content and deal highlights for price-sensitive users.",
    url: "https://www.flightsedge.co.uk/",
  },
  {
    title: "Flights to Turkey",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["Landing", "Route SEO"],
    desc: "Route-specific landing capturing Turkey-bound search intent.",
    url: "https://www.flights-to-turkey.co.uk/",
  },
  {
    title: "Hajj Umrah Hub",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["Laravel", "Content"],
    desc: "Hub-style browsing for pilgrimage travel resources and packages.",
    url: "https://www.hajjumrahhub.co.uk/",
  },
  {
    title: "Get Umrah Trip",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["Forms", "Conversion"],
    desc: "Conversion-oriented Umrah trip builder with structured inquiry steps.",
    url: "https://www.getumrahtrip.co.uk/",
  },
  {
    title: "Fly British",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["Bootstrap", "UK"],
    desc: "UK-centric flight branding with patriotic visual language and trust cues.",
    url: "https://www.flybritish.co.uk/",
  },
  {
    title: "Get Trip",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["PHP", "Travel"],
    desc: "Flexible trip discovery with multiple entry points into search and offers.",
    url: "https://www.gettrip.co.uk/",
  },
  {
    title: "Travel Terminal",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["JavaScript", "MySQL"],
    desc: "Multi-carrier offers presented in a single, terminal-style experience.",
    url: "https://travelterminal.co.uk/",
  },
  {
    title: "Jubilee Vacations (dev)",
    role: "Development",
    year: "2022 — Present",
    tags: ["Laravel", "Staging"],
    desc: "Dev build for vacation product experiments and pre-launch QA.",
    url: "https://dev.jubileevacations.com/",
  },
  {
    title: "Dua Tour",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["Canada", "Travel"],
    desc: "Canadian-market Islamic travel with clear package and contact flows.",
    url: "https://duatour.ca/",
  },
  {
    title: "Buraq Travel",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["Canada", "PHP"],
    desc: "Canada-based operator storytelling with emphasis on service and routes.",
    url: "https://buraqtravel.ca/",
  },
  {
    title: "Fly Route",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["Responsive", "Flights"],
    desc: "Route-forward flight presentation for domestic and international legs.",
    url: "https://flyroute.co.uk/",
  },
  {
    title: "Qibla Tain",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["Travel", "Content"],
    desc: "Brand built around Qibla and pilgrimage support with supportive guides.",
    url: "https://qiblatain.co.uk/",
  },
  {
    title: "Islamic Travel Agency (.com)",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["Global", "Laravel"],
    desc: "Global .com complement to regional sites — unified messaging and leads.",
    url: "https://islamictravelagency.com/",
  },
  {
    title: "The Cheapest Flight",
    role: "Full stack",
    year: "2022 — Present",
    tags: ["Deals", "SEO"],
    desc: "Price-led positioning for bargain hunters with aggressive offer framing.",
    url: "https://thecheapeastflight.co.uk/",
  },
] as const;

export type Project = (typeof projects)[number];
